FROM mcr.microsoft.com/dotnet/sdk:10.0-preview
WORKDIR /app

COPY CollaborationSystem.sln ./
COPY NuGet.config ./
COPY src ./src

RUN dotnet restore CollaborationSystem.sln
RUN dotnet build CollaborationSystem.sln -c Debug --no-restore

WORKDIR /app/src/CollaborationSystem.Api
EXPOSE 8080
CMD ["dotnet", "bin/Debug/net10.0/CollaborationSystem.Api.dll"]
