// <auto-generated />
using CollaborationSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CollaborationSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521120000_AddProjectMeetingsAndNormalizedFields")]
    partial class AddProjectMeetingsAndNormalizedFields
    {
    }
}
